config:
    profile: "D:/Desktop/FinalProj/Code/simplecq/config/profile.txt"
    restart_key: restart
models:
    - 
        dll_name: "D:/Desktop/FinalProj/Code/simplecq/bin/RelWithDebInfo/CarPhyModel.dll"
        model_name: phy
        output_movable: true
    - 
        dll_name: "D:/Desktop/FinalProj/Code/simplecq/bin/RelWithDebInfo/cq_interpreter.dll"
        model_name: beh
        output_movable: false
init_convert:
    - 
        to: phy
        values: 
            - {name: longitude}
            - {name: latitude}
            - {name: altitude}
    - 
        to: beh
        values:
            - {name: filePath}
            - {name: enableLog}
input_convert: 
    - 
        to: phy
        values:
            - {name: FireID}
            - {name: FireData}
            - {name: EntityInfo}
    - 
        to: beh
        values:
            - {name: targetPos}
            - {name: enableFire}
            - {name: formationID}
            - {name: fireTarget}
output_convert:
    - 
        from: phy
        values:
            - {name: State}
            - {name: VID}
            - {name: FireDataOut}
            - {name: EntityInfoOut}
            - {name: roll}
            - {name: yaw}
            - {name: pitch}
            - {name: longitude}
            - {name: latitude}
            - {name: altitude}
    - 
        from: phy
        to: beh
        values:
            - {name: roll}
            - {name: yaw}
            - {name: pitch}
            -
                src_name: EntityInfoOut
                dst_name: selfInfo
            - 
                src_name: scannedInfoOut
                dst_name: scannedInfo
            # - 
            #     src_name: weaponInfoOut
            #     dst_name: weaponInfo
    - 
        from: beh
        to: phy
        values:
            - {name: Param1}
            - {name: Param2}
            -
                src_name: ActionId
                dst_name: Command