model_type:
    -
        model_type_name: car
        dll_name: mymodel.dll
        output_movable: false
    -
        model_type_name: agent
        dll_name: mymodel.dll
        output_movable: false
models:
    -
        model_type: car
        side_id: 0
        id: 0
        init_value: "<c></c>"
topic:
    - 
        from: car
        members:
            - VID
            - FireDataOut
        subscribers:
            - 
                to: car
                name_convert:
                    -
                        src_name: VID
                        dst_name: FireID
                    - 
                        src_name: FireDataOut
                        dst_name: FireData